---
# Copyright (c) IBM Corporation 2021
# tasks file for common actions

# Execute SQL Query
- name: Copy SQL execution script
  ansible.builtin.template:
    src: roles/common/templates/run_sql.sh.j2
    dest: "{{ scripts_dir }}/run_sql_{{ database_name }}.sh"
    mode: '0755'

- name: Execute SQL script as "{{ db_oracle_user }}" for "{{ databases[database_name].db_sid }}"
  ansible.builtin.shell:
    cmd: "{{ scripts_dir }}/run_sql_{{ database_name }}.sh"
    executable: /bin/bash
  register: sql_output
  changed_when: false

- name: Set fact for SQL output
  ansible.builtin.set_fact:
    sql_query_output: "{{ sql_output.stdout_lines }}"